### PR TITLE
Switch to .NET 4.0

### PR DESCRIPTION
**Pull request by freeman**
We are still under .NET 4.0 for most of our project.

I ported this excellent library (thanks !) to .NET 4.0.

One method had to be sacrificied but I am not sure it is very used.

If you agree, would you consider merging it and publishing a new nuget version.

Thanks,

### CODE REVIEW

**Comment by davidwhitney** [comment]
this seems reasonable, i'll take a proper look this evening and see what i can do to publish a .net4 version.

**Comment by davidwhitney** [comment]
Hey - I think what I'm going to do is add an extra csproj for a .NET4 version of this and use a pre-processor directive around the incompatible method, rather than break backwards compatibility.

What this means:
* Not going to accept this PR
* I'll def. add .NET4 support
* I'll get a package out with multiple framework targets over the weekend

Make sense? :)

**Comment by freeman** [comment]
Looks cleaner than my approach but requires changes to the build process which is why I did not approach it this way.

Any idea on the build tool you will use ? (I heartily recommend FAKE :) )

**Comment by davidwhitney** [comment]
I've just published version 2.0.2.17 to nuget, which should introduce a version of the library compatible with 4.0 - try it out and let me know :+1:

**Comment by freeman** [comment]
Thanks this works great ! :+1:

**Pull request closed without merging**
